// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXCXoNAW4FcbO15WibYuSG_R9l6EV9uAc',
    appId: '1:1007661715456:web:1abd12327ada62a32d88e5',
    messagingSenderId: '1007661715456',
    projectId: 'vietrips-1ddeb',
    authDomain: 'vietrips-1ddeb.firebaseapp.com',
    storageBucket: 'vietrips-1ddeb.firebasestorage.app',
    measurementId: 'G-GLKD3VNZT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkRANk3J-qc7j-AplSJocLRlweJJMnYqM',
    appId: '1:1007661715456:android:887cff7abca68af62d88e5',
    messagingSenderId: '1007661715456',
    projectId: 'vietrips-1ddeb',
    storageBucket: 'vietrips-1ddeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEUb4ONMR1L0zDqHSaBhMlBbSZf7ASAFA',
    appId: '1:1007661715456:ios:370a00a4a452f8522d88e5',
    messagingSenderId: '1007661715456',
    projectId: 'vietrips-1ddeb',
    storageBucket: 'vietrips-1ddeb.firebasestorage.app',
    iosBundleId: 'com.example.vietour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXCXoNAW4FcbO15WibYuSG_R9l6EV9uAc',
    appId: '1:1007661715456:web:724f391d56a4a1e72d88e5',
    messagingSenderId: '1007661715456',
    projectId: 'vietrips-1ddeb',
    authDomain: 'vietrips-1ddeb.firebaseapp.com',
    storageBucket: 'vietrips-1ddeb.firebasestorage.app',
    measurementId: 'G-4G84ZK03K3',
  );
}
